<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Payment;
use AppBundle\Entity\Payment_Method;
use Doctrine\Common\Collections\Expr\Comparison;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends \Doctrine\ORM\EntityRepository
{

    public function findWithAllFilters($paymentMethod, $company, $payment_date_from, $payment_date_until): array
    {
        $qb = $this->createQueryBuilder('p');

        if ($payment_date_from && $payment_date_until) {
            $qb->add('where', $qb->expr()->between(
                'p.paymentDate',
                ':from',
                ':to'
                    )
                )
            ->setParameters(array('from' => $payment_date_from, 'to' => $payment_date_until)); 
        }
        
        if ($paymentMethod) {            
            $wherePMethod = 'p.paymentMethod = '.$paymentMethod;
            $qb->andWhere($wherePMethod);
        }

        if ($company) {            
            $whereCompany = 'p.company = '.$company;
            $qb->andWhere($whereCompany); 
        }


        $query = $qb->getQuery();

        return $query->execute();
    }

}
