<?php

namespace AppBundle\Repository;

/**
 * Payment_MethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Payment_MethodRepository extends \Doctrine\ORM\EntityRepository
{
}
